name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        id: deploy
        run: |
          git config --global user.name "Shreyas Panicker"
          git config --global user.email "panickershreyas@gmail.com"
          git checkout -b gh-pages
          git add -f dist
          git commit -m "Deploying to GitHub Pages"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Deployment Status
        run: echo "deployment-status=success" >> $GITHUB_ENV

      - name: Set Published URL as Output
        run: echo "::set-output name=published_url::https://$GITHUB_REPOSITORY.github.io"
